import { useLanguage } from "@/context/LanguageContext";

export const bankToolsUIContent = {
  fa: {
    tools: {
      loan: {
        name: "محاسبه سود و اقساط وام",
        desc: "محاسبه مبلغ اقساط ماهانه و سود کل وام",
      },
      deposit: {
        name: "محاسبه سود سپرده بانکی",
        desc: "محاسبه سود روزشمار، ماهانه و سالانه",
      },
      installment: {
        name: "محاسبه خرید اقساطی در بازار",
        desc: "محاسبه سود یا قسط در خرید و فروش",
      },
      saving: {
        name: "محاسبه پس‌انداز پول",
        desc: "محاسبه رشد پس‌انداز در طول زمان",
      },
      expense: {
        name: "مدیریت هزینه و درآمد",
        desc: "پیگیری هزینه‌ها و درآمدها به سادگی",
      },
      prices: {
        name: "قیمت سکه، طلا و ارز",
        desc: "قیمت لحظه ای سکه، طلا و ارز",
      },
    },
    common: {
      calculate: "محاسبه",
      result: "نتیجه",
      clear: "پاک کردن",
      add: "افزودن",
      delete: "حذف",
      edit: "ویرایش",
      save: "ذخیره",
      cancel: "لغو",
      total: "مجموع",
      details: "جزئیات",
      chart: "نمودار",
      export: "خروجی",
      selectTool: "انتخاب ابزار",
      currency: "تومان",
      date: "تاریخ",
      amount: "مبلغ",
      description: "توضیحات",
      category: "دسته‌بندی",
    },
    loan: {
      labels: {
        loanAmount: "مبلغ وام (تومان)",
        interestRate: "نرخ سود سالانه (%)",
        loanTerm: "مدت وام (ماه)",
        monthlyPayment: "قسط ماهانه",
        totalPayment: "مجموع پرداختی",
        totalInterest: "مجموع سود",
        paymentSchedule: "جدول اقساط",
        month: "ماه",
        principal: "اصل وام",
        interest: "سود",
        balance: "مانده",
        payment: "پرداختی",
      },
      types: {
        fixed: "سود ثابت",
        reducing: "سود نزولی",
      },
      hints: {
        loanAmount: "مبلغ وام مورد نیاز را وارد کنید",
        interestRate: "نرخ سود سالانه بانک (معمولاً 18-24%)",
        loanTerm: "تعداد ماه‌های بازپرداخت",
      },
    },
    deposit: {
      labels: {
        principal: "مبلغ اولیه (تومان)",
        rate: "نرخ سود سالانه (%)",
        duration: "مدت زمان",
        compoundFrequency: "دوره تجمیع سود",
        finalAmount: "مبلغ نهایی",
        earnedInterest: "سود کسب شده",
        effectiveRate: "نرخ موثر",
      },
      periods: {
        daily: "روزانه",
        monthly: "ماهانه",
        quarterly: "سه‌ماهه",
        yearly: "سالانه",
      },
      durations: {
        days: "روز",
        months: "ماه",
        years: "سال",
      },
      hints: {
        principal: "مبلغی که می‌خواهید سپرده‌گذاری کنید",
        rate: "نرخ سود سالانه بانک (معمولاً 15-20%)",
        duration: "مدت زمان نگهداری سپرده",
      },
    },
    installment: {
      labels: {
        cashPrice: "قیمت نقدی (تومان)",
        downPayment: "پیش‌پرداخت (تومان)",
        numberOfInstallments: "تعداد اقساط",
        interestRate: "نرخ سود (%)",
        monthlyInstallment: "قسط ماهانه",
        totalPrice: "قیمت کل",
        extraCost: "هزینه اضافی",
        installmentSchedule: "جدول اقساط",
      },
      modes: {
        calculate: "محاسبه قسط",
        compare: "مقایسه نقد و اقساط",
      },
      hints: {
        cashPrice: "قیمت کالا در صورت خرید نقدی",
        downPayment: "مبلغ پیش‌پرداخت (اختیاری)",
        numberOfInstallments: "تعداد اقساط (معمولاً 3، 6، 12 ماه)",
      },
    },
    saving: {
      labels: {
        initialAmount: "مبلغ اولیه (تومان)",
        monthlyDeposit: "واریز ماهانه (تومان)",
        annualReturn: "بازده سالانه (%)",
        period: "مدت زمان (سال)",
        finalValue: "ارزش نهایی",
        totalDeposited: "مجموع واریزی",
        totalEarned: "مجموع سود",
        yearlyBreakdown: "تفکیک سالانه",
        year: "سال",
        deposits: "واریزی",
        interest: "سود",
        balance: "موجودی",
      },
      scenarios: {
        conservative: "محافظه‌کارانه (10%)",
        moderate: "متعادل (15%)",
        aggressive: "پرریسک (20%)",
        custom: "سفارشی",
      },
      hints: {
        initialAmount: "مبلغی که در ابتدا دارید",
        monthlyDeposit: "مبلغی که هر ماه پس‌انداز می‌کنید",
        annualReturn: "بازده مورد انتظار (بر اساس نوع سرمایه‌گذاری)",
      },
    },
    expense: {
      labels: {
        type: "نوع",
        income: "درآمد",
        expense: "هزینه",
        balance: "مانده",
        totalIncome: "مجموع درآمد",
        totalExpense: "مجموع هزینه",
        netBalance: "موجودی خالص",
        addTransaction: "افزودن تراکنش",
        transactions: "تراکنش‌ها",
        filter: "فیلتر",
        all: "همه",
        thisMonth: "این ماه",
        thisYear: "امسال",
        custom: "سفارشی",
        from: "از",
        to: "تا",
      },
      categories: {
        income: {
          salary: "حقوق",
          business: "کسب‌وکار",
          investment: "سرمایه‌گذاری",
          other: "سایر",
        },
        expense: {
          food: "خوراک",
          transport: "حمل‌ونقل",
          housing: "مسکن",
          health: "بهداشت",
          education: "آموزش",
          entertainment: "سرگرمی",
          shopping: "خرید",
          bills: "قبوض",
          other: "سایر",
        },
      },
      hints: {
        amount: "مبلغ تراکنش را وارد کنید",
        description: "توضیحات اختیاری",
        category: "دسته‌بندی تراکنش",
      },
    },
    prices: {
      labels: {
        gold: "طلا",
        coin: "سکه",
        currency: "ارز",
        lastUpdate: "آخرین بروزرسانی",
        price: "قیمت",
        change: "تغییرات",
        high: "بیشترین",
        low: "کمترین",
        refreshing: "در حال بروزرسانی...",
        refresh: "بروزرسانی",
        unit: "واحد",
      },
      gold: {
        gram18: "طلای 18 عیار (گرم)",
        gram24: "طلای 24 عیار (گرم)",
        mesghal: "مثقال طلا",
        ounce: "اونس طلا",
      },
      coin: {
        emami: "سکه امامی",
        bahar: "سکه بهار آزادی",
        half: "نیم سکه",
        quarter: "ربع سکه",
        gerami: "سکه گرمی",
      },
      currency: {
        usd: "دلار آمریکا",
        eur: "یورو",
        gbp: "پوند انگلیس",
        try: "لیر ترکیه",
        aed: "درهم امارات",
      },
      errors: {
        fetchFailed: "خطا در دریافت قیمت‌ها",
        tryAgain: "لطفاً دوباره تلاش کنید",
      },
    },
  },
  en: {
    tools: {
      loan: {
        name: "Loan & Interest Calculator",
        desc: "Calculate monthly installments and total loan interest",
      },
      deposit: {
        name: "Bank Deposit Calculator",
        desc: "Calculate daily, monthly, and annual interest",
      },
      installment: {
        name: "Installment Purchase Calculator",
        desc: "Calculate interest or installment in buying and selling",
      },
      saving: {
        name: "Savings Calculator",
        desc: "Calculate savings growth over time",
      },
      expense: {
        name: "Expense & Income Manager",
        desc: "Track expenses and income easily",
      },
      prices: {
        name: "Gold, Coin & Currency Prices",
        desc: "Live prices of gold, coins and currencies",
      },
    },
    common: {
      calculate: "Calculate",
      result: "Result",
      clear: "Clear",
      add: "Add",
      delete: "Delete",
      edit: "Edit",
      save: "Save",
      cancel: "Cancel",
      total: "Total",
      details: "Details",
      chart: "Chart",
      export: "Export",
      selectTool: "Select Tool",
      currency: "USD",
      date: "Date",
      amount: "Amount",
      description: "Description",
      category: "Category",
    },
    loan: {
      labels: {
        loanAmount: "Loan Amount (USD)",
        interestRate: "Annual Interest Rate (%)",
        loanTerm: "Loan Term (months)",
        monthlyPayment: "Monthly Payment",
        totalPayment: "Total Payment",
        totalInterest: "Total Interest",
        paymentSchedule: "Payment Schedule",
        month: "Month",
        principal: "Principal",
        interest: "Interest",
        balance: "Balance",
        payment: "Payment",
      },
      types: {
        fixed: "Fixed Interest",
        reducing: "Reducing Balance",
      },
      hints: {
        loanAmount: "Enter the required loan amount",
        interestRate: "Bank annual interest rate (usually 5-10%)",
        loanTerm: "Number of months for repayment",
      },
    },
    deposit: {
      labels: {
        principal: "Initial Amount (USD)",
        rate: "Annual Interest Rate (%)",
        duration: "Duration",
        compoundFrequency: "Compound Frequency",
        finalAmount: "Final Amount",
        earnedInterest: "Earned Interest",
        effectiveRate: "Effective Rate",
      },
      periods: {
        daily: "Daily",
        monthly: "Monthly",
        quarterly: "Quarterly",
        yearly: "Yearly",
      },
      durations: {
        days: "Days",
        months: "Months",
        years: "Years",
      },
      hints: {
        principal: "Amount you want to deposit",
        rate: "Bank annual interest rate (usually 2-5%)",
        duration: "Deposit holding period",
      },
    },
    installment: {
      labels: {
        cashPrice: "Cash Price (USD)",
        downPayment: "Down Payment (USD)",
        numberOfInstallments: "Number of Installments",
        interestRate: "Interest Rate (%)",
        monthlyInstallment: "Monthly Installment",
        totalPrice: "Total Price",
        extraCost: "Extra Cost",
        installmentSchedule: "Installment Schedule",
      },
      modes: {
        calculate: "Calculate Installment",
        compare: "Compare Cash vs Installment",
      },
      hints: {
        cashPrice: "Product price for cash purchase",
        downPayment: "Down payment amount (optional)",
        numberOfInstallments:
          "Number of installments (usually 3, 6, 12 months)",
      },
    },
    saving: {
      labels: {
        initialAmount: "Initial Amount (USD)",
        monthlyDeposit: "Monthly Deposit (USD)",
        annualReturn: "Annual Return (%)",
        period: "Period (years)",
        finalValue: "Final Value",
        totalDeposited: "Total Deposited",
        totalEarned: "Total Earned",
        yearlyBreakdown: "Yearly Breakdown",
        year: "Year",
        deposits: "Deposits",
        interest: "Interest",
        balance: "Balance",
      },
      scenarios: {
        conservative: "Conservative (5%)",
        moderate: "Moderate (8%)",
        aggressive: "Aggressive (12%)",
        custom: "Custom",
      },
      hints: {
        initialAmount: "Amount you have initially",
        monthlyDeposit: "Amount you save each month",
        annualReturn: "Expected return (based on investment type)",
      },
    },
    expense: {
      labels: {
        type: "Type",
        income: "Income",
        expense: "Expense",
        balance: "Balance",
        totalIncome: "Total Income",
        totalExpense: "Total Expense",
        netBalance: "Net Balance",
        addTransaction: "Add Transaction",
        transactions: "Transactions",
        filter: "Filter",
        all: "All",
        thisMonth: "This Month",
        thisYear: "This Year",
        custom: "Custom",
        from: "From",
        to: "To",
      },
      categories: {
        income: {
          salary: "Salary",
          business: "Business",
          investment: "Investment",
          other: "Other",
        },
        expense: {
          food: "Food",
          transport: "Transport",
          housing: "Housing",
          health: "Health",
          education: "Education",
          entertainment: "Entertainment",
          shopping: "Shopping",
          bills: "Bills",
          other: "Other",
        },
      },
      hints: {
        amount: "Enter transaction amount",
        description: "Optional description",
        category: "Transaction category",
      },
    },
    prices: {
      labels: {
        gold: "Gold",
        coin: "Coin",
        currency: "Currency",
        lastUpdate: "Last Update",
        price: "Price",
        change: "Change",
        high: "High",
        low: "Low",
        refreshing: "Refreshing...",
        refresh: "Refresh",
        unit: "Unit",
      },
      gold: {
        gram18: "18K Gold (gram)",
        gram24: "24K Gold (gram)",
        mesghal: "Mesghal Gold",
        ounce: "Gold Ounce",
      },
      coin: {
        emami: "Emami Coin",
        bahar: "Bahar Azadi Coin",
        half: "Half Coin",
        quarter: "Quarter Coin",
        gerami: "Gerami Coin",
      },
      currency: {
        usd: "US Dollar",
        eur: "Euro",
        gbp: "British Pound",
        try: "Turkish Lira",
        aed: "UAE Dirham",
      },
      errors: {
        fetchFailed: "Failed to fetch prices",
        tryAgain: "Please try again",
      },
    },
  },
};

export type BankToolsContent = typeof bankToolsUIContent.fa;

export function useBankToolsUIContent() {
  const { locale } = useLanguage();
  return bankToolsUIContent[locale];
}
