// components/tools/security/security-tools/security-tools.content.ts

import { useLanguage } from "@/context/LanguageContext";

export const securityToolsUIContent = {
  fa: {
    tools: {
      qrScanner: {
        name: "اسکن QR Code",
        desc: "اسکن کد QR سریع و دقیق",
      },
      barcodeGenerator: {
        name: "ساخت بارکد",
        desc: "ایجاد بارکد حرفه‌ای",
      },
      aesEncryption: {
        name: "رمزنگاری/رمزگشایی AES",
        desc: "رمزنگاری و رمزگشایی متن با AES",
      },
      oneTimeNote: {
        name: "یادداشت یکبارمصرف",
        desc: "ارسال یادداشت موقت رمزگذاری شده",
      },
      htmlToText: {
        name: "HTML به متن",
        desc: "تبدیل HTML به متن ساده",
      },
      textToMorse: {
        name: "متن ↔ کد مورس",
        desc: "تبدیل متن به کد مورس و برعکس",
      },
      textToBinary: {
        name: "متن ↔ باینری",
        desc: "تبدیل متن به باینری و برعکس",
      },
      textToHex: {
        name: "متن ↔ هگز",
        desc: "تبدیل متن به هگزادسیمال و برعکس",
      },
    },
    common: {
      selectTool: "انتخاب ابزار",
      input: "ورودی",
      output: "خروجی",
      convert: "تبدیل",
      encrypt: "رمزنگاری",
      decrypt: "رمزگشایی",
      scan: "اسکن",
      generate: "ساخت",
      copy: "کپی",
      paste: "جایگذاری",
      clear: "پاک کردن",
      download: "دانلود",
      upload: "آپلود",
      result: "نتیجه",
      copied: "کپی شد!",
      error: "خطا",
      success: "موفق",
    },
    qrScanner: {
      title: "اسکن QR Code",
      uploadImage: "آپلود تصویر",
      useCamera: "استفاده از دوربین",
      result: "نتیجه اسکن",
      noResult: "کدی شناسایی نشد",
      scanning: "در حال اسکن...",
      selectImage: "یک تصویر انتخاب کنید",
    },
    barcodeGenerator: {
      title: "ساخت بارکد",
      inputText: "متن یا عدد",
      barcodeType: "نوع بارکد",
      width: "عرض",
      height: "ارتفاع",
      displayValue: "نمایش متن",
      backgroundColor: "رنگ پس‌زمینه",
      lineColor: "رنگ خط",
      types: {
        CODE128: "CODE128 (متن و عدد)",
        EAN13: "EAN13 (13 رقم)",
        UPC: "UPC (12 رقم)",
        CODE39: "CODE39 (متن و عدد)",
        ITF14: "ITF14 (14 رقم)",
      },
    },
    aesEncryption: {
      title: "رمزنگاری AES",
      plainText: "متن اصلی",
      encryptedText: "متن رمزشده",
      secretKey: "کلید رمز (Secret Key)",
      mode: "حالت",
      encrypt: "رمزنگاری",
      decrypt: "رمزگشایی",
      keyHint: "کلید باید حداقل 16 کاراکتر باشد",
      invalidKey: "کلید نامعتبر است",
    },
    oneTimeNote: {
      title: "یادداشت یکبارمصرف",
      noteContent: "محتوای یادداشت",
      expiresIn: "انقضا پس از",
      maxViews: "حداکثر مشاهده",
      password: "رمز عبور (اختیاری)",
      createNote: "ساخت یادداشت",
      noteLink: "لینک یادداشت",
      copyLink: "کپی لینک",
      linkCopied: "لینک کپی شد!",
      noteCreated: "یادداشت ساخته شد",
      expires: {
        "5m": "5 دقیقه",
        "1h": "1 ساعت",
        "24h": "24 ساعت",
        "7d": "7 روز",
      },
      views: {
        "1": "1 بار",
        "5": "5 بار",
        "10": "10 بار",
        unlimited: "نامحدود",
      },
    },
    htmlToText: {
      title: "HTML به متن",
      htmlInput: "کد HTML",
      textOutput: "متن خروجی",
      removeLinks: "حذف لینک‌ها",
      preserveFormatting: "حفظ فرمت",
    },
    textToMorse: {
      title: "متن ↔ کد مورس",
      textInput: "متن",
      morseOutput: "کد مورس",
      toMorse: "به مورس",
      toText: "به متن",
      playSound: "پخش صدا",
    },
    textToBinary: {
      title: "متن ↔ باینری",
      textInput: "متن",
      binaryOutput: "باینری",
      toBinary: "به باینری",
      toText: "به متن",
      separator: "جداکننده",
      separators: {
        space: "فاصله",
        comma: "کاما",
        none: "بدون",
      },
    },
    textToHex: {
      title: "متن ↔ هگز",
      textInput: "متن",
      hexOutput: "هگزادسیمال",
      toHex: "به هگز",
      toText: "به متن",
      uppercase: "حروف بزرگ",
      prefix: "پیشوند 0x",
    },
  },
  en: {
    tools: {
      qrScanner: {
        name: "QR Code Scanner",
        desc: "Fast and accurate QR code scanning",
      },
      barcodeGenerator: {
        name: "Barcode Generator",
        desc: "Create professional barcodes",
      },
      aesEncryption: {
        name: "AES Encryption/Decryption",
        desc: "Encrypt and decrypt text with AES",
      },
      oneTimeNote: {
        name: "One-Time Note",
        desc: "Send temporary encrypted notes",
      },
      htmlToText: {
        name: "HTML to Text",
        desc: "Convert HTML to plain text",
      },
      textToMorse: {
        name: "Text ↔ Morse Code",
        desc: "Convert text to morse code and vice versa",
      },
      textToBinary: {
        name: "Text ↔ Binary",
        desc: "Convert text to binary and vice versa",
      },
      textToHex: {
        name: "Text ↔ Hex",
        desc: "Convert text to hexadecimal and vice versa",
      },
    },
    common: {
      selectTool: "Select Tool",
      input: "Input",
      output: "Output",
      convert: "Convert",
      encrypt: "Encrypt",
      decrypt: "Decrypt",
      scan: "Scan",
      generate: "Generate",
      copy: "Copy",
      paste: "Paste",
      clear: "Clear",
      download: "Download",
      upload: "Upload",
      result: "Result",
      copied: "Copied!",
      error: "Error",
      success: "Success",
    },
    qrScanner: {
      title: "QR Code Scanner",
      uploadImage: "Upload Image",
      useCamera: "Use Camera",
      result: "Scan Result",
      noResult: "No code detected",
      scanning: "Scanning...",
      selectImage: "Select an image",
    },
    barcodeGenerator: {
      title: "Barcode Generator",
      inputText: "Text or Number",
      barcodeType: "Barcode Type",
      width: "Width",
      height: "Height",
      displayValue: "Display Text",
      backgroundColor: "Background Color",
      lineColor: "Line Color",
      types: {
        CODE128: "CODE128 (Text & Numbers)",
        EAN13: "EAN13 (13 digits)",
        UPC: "UPC (12 digits)",
        CODE39: "CODE39 (Text & Numbers)",
        ITF14: "ITF14 (14 digits)",
      },
    },
    aesEncryption: {
      title: "AES Encryption",
      plainText: "Plain Text",
      encryptedText: "Encrypted Text",
      secretKey: "Secret Key",
      mode: "Mode",
      encrypt: "Encrypt",
      decrypt: "Decrypt",
      keyHint: "Key must be at least 16 characters",
      invalidKey: "Invalid key",
    },
    oneTimeNote: {
      title: "One-Time Note",
      noteContent: "Note Content",
      expiresIn: "Expires In",
      maxViews: "Max Views",
      password: "Password (optional)",
      createNote: "Create Note",
      noteLink: "Note Link",
      copyLink: "Copy Link",
      linkCopied: "Link copied!",
      noteCreated: "Note created",
      expires: {
        "5m": "5 minutes",
        "1h": "1 hour",
        "24h": "24 hours",
        "7d": "7 days",
      },
      views: {
        "1": "1 time",
        "5": "5 times",
        "10": "10 times",
        unlimited: "Unlimited",
      },
    },
    htmlToText: {
      title: "HTML to Text",
      htmlInput: "HTML Code",
      textOutput: "Text Output",
      removeLinks: "Remove Links",
      preserveFormatting: "Preserve Formatting",
    },
    textToMorse: {
      title: "Text ↔ Morse Code",
      textInput: "Text",
      morseOutput: "Morse Code",
      toMorse: "To Morse",
      toText: "To Text",
      playSound: "Play Sound",
    },
    textToBinary: {
      title: "Text ↔ Binary",
      textInput: "Text",
      binaryOutput: "Binary",
      toBinary: "To Binary",
      toText: "To Text",
      separator: "Separator",
      separators: {
        space: "Space",
        comma: "Comma",
        none: "None",
      },
    },
    textToHex: {
      title: "Text ↔ Hex",
      textInput: "Text",
      hexOutput: "Hexadecimal",
      toHex: "To Hex",
      toText: "To Text",
      uppercase: "Uppercase",
      prefix: "0x Prefix",
    },
  },
};

export type SecurityToolsUIContent = typeof securityToolsUIContent.fa;

export function useSecurityToolsUIContent() {
  const { locale } = useLanguage();
  return securityToolsUIContent[locale];
}
